FROM ubuntu:20.04

ENV TZ=Europe/Copenhagen
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update
RUN apt install cmake libmbedtls-dev libgmp3-dev wget git python3 python3-pip -y

RUN wget https://libntl.org/ntl-11.5.1.tar.gz
RUN tar -xvf ntl-11.5.1.tar.gz

WORKDIR "/ntl-11.5.1/src"

RUN bash configure SHARED=on
RUN make
RUN make check
RUN make install

WORKDIR "/"
RUN git clone https://github.com/Xtra-Computing/FedTree.git

WORKDIR "/FedTree" 
RUN git submodule init
RUN git submodule update
RUN mkdir build

WORKDIR "/FedTree/build"
RUN cmake .. -DNTL_PATH="/ntl-11.5.1"
RUN make -j 4

